### ISSUE TITLE
Macro function does not get invoked

### ISSUE THREAD

**Issue by MatteoInfi** [lumigo/SAR-cloudwatch-alarms-macro#11]
Upon deploying my template the macro function does not get invoked and it cannot create the alarms. 
Do I need to add any permission?

```
  SARCloudwatchAlarmsLayer:
    Type: AWS::Serverless::Application
    Condition: IsProduction
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/cloudwatch-alarms-macro
        SemanticVersion: 1.0.3
      Parameters:
        DefaultConfigParamName:<my param name>

```
