### ISSUE TITLE
The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda

### ISSUE THREAD

**Issue by rudijs** [lumigo/SAR-cloudwatch-alarms-macro#6]
Hi,

Seeing this error, sorry I'm only familiar with the serverless framework - my SAM skills are very early stage so I'm not sure how to test out a change before making a pull request.

```
    "eventTime": "2020-06-23T16:22:32Z",
    "eventSource": "lambda.amazonaws.com",
    "eventName": "CreateFunction20150331",
    "awsRegion": "ap-southeast-1",
    "sourceIPAddress": "cloudformation.amazonaws.com",
    "userAgent": "cloudformation.amazonaws.com",
    "errorCode": "InvalidParameterValueException",
    "errorMessage": "The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.",
    "requestParameters": {
        "functionName": "user-api-dev-cloudwatchala-TransformLambdaFunction-10LP1JJ5QUCIU",
        "runtime": "nodejs8.10",
```

**Comment by MatteoInfi** [comment]
I am getting the same error, probably the serverless repo has not been update

**Comment by MatteoInfi** [comment]
Ok, I have found a solution. Unfortunately is not very intuitive, but if you click on `deploy` from this link: https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:374852340823:applications~cloudwatch-alarms-macro

the screen that will open will show the version you have to input in your template, version `1.0.0` is still pointing to the old code, while the current version is: `1.0.3`

```
  SARCloudwatchAlarmsLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/cloudwatch-alarms-macro
        SemanticVersion: 1.0.3
      Parameters:
        DefaultConfigParamName: <your param name>
```

I hope this helps
